version: '3.3'
services:
  web:
    container_name: web
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - database
  database:
    container_name: db_zee
    image: postgis/postgis:13-3.3
    restart: always
    ports:
      - "5444:5432"
    environment:
      - LC_ALL=C.UTF-8
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=db_zee
    volumes:
      - postgres_data:/var/lib/postgresql/data/
      - type: tmpfs
        target: /dev/shm
  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "email@gmail.com"
      PGADMIN_DEFAULT_PASSWORD: "email123"
      PGADMIN_LISTEN_PORT: 80
    ports:
      - "5011:80"
volumes:
  postgres_data: